// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_pdist2
arma::mat compute_pdist2(arma::mat& X, arma::mat& Y);
RcppExport SEXP _T4transport_compute_pdist2(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_pdist2(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mvrnorm
arma::mat cpp_mvrnorm(int n, const arma::vec& mu, const arma::mat& cov);
RcppExport SEXP _T4transport_cpp_mvrnorm(SEXP nSEXP, SEXP muSEXP, SEXP covSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cov(covSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mvrnorm(n, mu, cov));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ipot20
Rcpp::List cpp_ipot20(const arma::vec a, const arma::vec b, const arma::mat& dab, double lambda, double p, int maxiter, double abstol, int L);
RcppExport SEXP _T4transport_cpp_ipot20(SEXP aSEXP, SEXP bSEXP, SEXP dabSEXP, SEXP lambdaSEXP, SEXP pSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dab(dabSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ipot20(a, b, dab, lambda, p, maxiter, abstol, L));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pwdist
Rcpp::List cpp_pwdist(const arma::mat& X, const arma::vec& p, const arma::mat& Y, const arma::vec& q, int maxiter, double abstol);
RcppExport SEXP _T4transport_cpp_pwdist(SEXP XSEXP, SEXP pSEXP, SEXP YSEXP, SEXP qSEXP, SEXP maxiterSEXP, SEXP abstolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pwdist(X, p, Y, q, maxiter, abstol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sinkhorn13
Rcpp::List cpp_sinkhorn13(const arma::vec a, const arma::vec b, const arma::mat& dab, double lambda, double p, int maxiter, double abstol);
RcppExport SEXP _T4transport_cpp_sinkhorn13(SEXP aSEXP, SEXP bSEXP, SEXP dabSEXP, SEXP lambdaSEXP, SEXP pSEXP, SEXP maxiterSEXP, SEXP abstolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dab(dabSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sinkhorn13(a, b, dab, lambda, p, maxiter, abstol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_barybregman15
arma::vec cpp_barybregman15(arma::field<arma::mat>& listdXY, arma::field<arma::vec>& marginals, arma::vec weights, double p, double lambda, int maxiter, double abstol, bool printer, arma::vec initvec);
RcppExport SEXP _T4transport_cpp_barybregman15(SEXP listdXYSEXP, SEXP marginalsSEXP, SEXP weightsSEXP, SEXP pSEXP, SEXP lambdaSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP printerSEXP, SEXP initvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat>& >::type listdXY(listdXYSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec>& >::type marginals(marginalsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< bool >::type printer(printerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type initvec(initvecSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_barybregman15(listdXY, marginals, weights, p, lambda, maxiter, abstol, printer, initvec));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fixed_sinkhorn14
arma::vec cpp_fixed_sinkhorn14(arma::field<arma::mat>& listdXY, arma::field<arma::vec>& marginals, arma::vec weights, double p, double lambda, int maxiter, double abstol, bool printer, arma::vec initvec);
RcppExport SEXP _T4transport_cpp_fixed_sinkhorn14(SEXP listdXYSEXP, SEXP marginalsSEXP, SEXP weightsSEXP, SEXP pSEXP, SEXP lambdaSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP printerSEXP, SEXP initvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::field<arma::mat>& >::type listdXY(listdXYSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec>& >::type marginals(marginalsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< bool >::type printer(printerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type initvec(initvecSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fixed_sinkhorn14(listdXY, marginals, weights, p, lambda, maxiter, abstol, printer, initvec));
    return rcpp_result_gen;
END_RCPP
}
// cpp_free_bary_gradient
Rcpp::List cpp_free_bary_gradient(const arma::field<arma::mat>& measures, const arma::field<arma::vec>& marginals, const arma::vec& weights, int num_support, int maxiter, double abstol);
RcppExport SEXP _T4transport_cpp_free_bary_gradient(SEXP measuresSEXP, SEXP marginalsSEXP, SEXP weightsSEXP, SEXP num_supportSEXP, SEXP maxiterSEXP, SEXP abstolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type measures(measuresSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::vec>& >::type marginals(marginalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type num_support(num_supportSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_free_bary_gradient(measures, marginals, weights, num_support, maxiter, abstol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_single_barycenter
arma::mat cpp_single_barycenter(const arma::field<arma::mat>& measures, const arma::field<arma::vec>& marginals, const arma::vec& weights, arma::mat& init_support);
RcppExport SEXP _T4transport_cpp_single_barycenter(SEXP measuresSEXP, SEXP marginalsSEXP, SEXP weightsSEXP, SEXP init_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type measures(measuresSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::vec>& >::type marginals(marginalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type init_support(init_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_single_barycenter(measures, marginals, weights, init_support));
    return rcpp_result_gen;
END_RCPP
}
// cpp_free_bary_gradient_init
Rcpp::List cpp_free_bary_gradient_init(const arma::field<arma::mat>& measures, const arma::field<arma::vec>& marginals, const arma::vec& weights, int maxiter, double abstol, arma::mat& init_support);
RcppExport SEXP _T4transport_cpp_free_bary_gradient_init(SEXP measuresSEXP, SEXP marginalsSEXP, SEXP weightsSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP init_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type measures(measuresSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::vec>& >::type marginals(marginalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type init_support(init_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_free_bary_gradient_init(measures, marginals, weights, maxiter, abstol, init_support));
    return rcpp_result_gen;
END_RCPP
}
// cpp_free_median_PF
Rcpp::List cpp_free_median_PF(const arma::field<arma::mat>& measures, const arma::field<arma::vec>& marginals, const arma::vec& weights, int maxiter, double abstol, arma::mat& init_support);
RcppExport SEXP _T4transport_cpp_free_median_PF(SEXP measuresSEXP, SEXP marginalsSEXP, SEXP weightsSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP init_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type measures(measuresSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::vec>& >::type marginals(marginalsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type init_support(init_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_free_median_PF(measures, marginals, weights, maxiter, abstol, init_support));
    return rcpp_result_gen;
END_RCPP
}
// gauss_weiszfeld
arma::rowvec gauss_weiszfeld(arma::mat& X, arma::vec& weights, double abstol, int maxiter);
RcppExport SEXP _T4transport_gauss_weiszfeld(SEXP XSEXP, SEXP weightsSEXP, SEXP abstolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_weiszfeld(X, weights, abstol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// gauss_spdbary16A
arma::mat gauss_spdbary16A(arma::cube array3d, arma::vec weight, double abstol, int maxiter);
RcppExport SEXP _T4transport_gauss_spdbary16A(SEXP array3dSEXP, SEXP weightSEXP, SEXP abstolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type array3d(array3dSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_spdbary16A(array3d, weight, abstol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// gauss_median_general
Rcpp::List gauss_median_general(arma::mat& mean2d, arma::cube& array3d, arma::vec& weight, double abstol, int maxiter);
RcppExport SEXP _T4transport_gauss_median_general(SEXP mean2dSEXP, SEXP array3dSEXP, SEXP weightSEXP, SEXP abstolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type mean2d(mean2dSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type array3d(array3dSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_median_general(mean2d, array3d, weight, abstol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// gauss_median_centered
arma::mat gauss_median_centered(arma::cube& array3d, arma::vec& weight, double abstol, int maxiter);
RcppExport SEXP _T4transport_gauss_median_centered(SEXP array3dSEXP, SEXP weightSEXP, SEXP abstolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type array3d(array3dSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_median_centered(array3d, weight, abstol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// routine_bary14C
arma::vec routine_bary14C(arma::mat& dxy, arma::field<arma::vec>& marginals, arma::vec weights, double p, double lambda, int maxiter, double abstol, bool printer, arma::vec initvec, int nthread);
RcppExport SEXP _T4transport_routine_bary14C(SEXP dxySEXP, SEXP marginalsSEXP, SEXP weightsSEXP, SEXP pSEXP, SEXP lambdaSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP printerSEXP, SEXP initvecSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type dxy(dxySEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec>& >::type marginals(marginalsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< bool >::type printer(printerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type initvec(initvecSEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(routine_bary14C(dxy, marginals, weights, p, lambda, maxiter, abstol, printer, initvec, nthread));
    return rcpp_result_gen;
END_RCPP
}
// routine_bary15B
arma::vec routine_bary15B(arma::mat& dxy, arma::field<arma::vec>& marginals, arma::vec weights, double p, double lambda, int maxiter, double abstol, bool printer, arma::vec initvec, int nthread);
RcppExport SEXP _T4transport_routine_bary15B(SEXP dxySEXP, SEXP marginalsSEXP, SEXP weightsSEXP, SEXP pSEXP, SEXP lambdaSEXP, SEXP maxiterSEXP, SEXP abstolSEXP, SEXP printerSEXP, SEXP initvecSEXP, SEXP nthreadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type dxy(dxySEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec>& >::type marginals(marginalsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type abstol(abstolSEXP);
    Rcpp::traits::input_parameter< bool >::type printer(printerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type initvec(initvecSEXP);
    Rcpp::traits::input_parameter< int >::type nthread(nthreadSEXP);
    rcpp_result_gen = Rcpp::wrap(routine_bary15B(dxy, marginals, weights, p, lambda, maxiter, abstol, printer, initvec, nthread));
    return rcpp_result_gen;
END_RCPP
}
// util_mvrnorm
arma::mat util_mvrnorm(const arma::vec& par_mean, const arma::mat& par_cov, int num_samples);
RcppExport SEXP _T4transport_util_mvrnorm(SEXP par_meanSEXP, SEXP par_covSEXP, SEXP num_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type par_mean(par_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type par_cov(par_covSEXP);
    Rcpp::traits::input_parameter< int >::type num_samples(num_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(util_mvrnorm(par_mean, par_cov, num_samples));
    return rcpp_result_gen;
END_RCPP
}
// util_pairwise_sqdist
arma::mat util_pairwise_sqdist(const arma::mat& X, const arma::mat& Y);
RcppExport SEXP _T4transport_util_pairwise_sqdist(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(util_pairwise_sqdist(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// util_pairwise_dist
arma::mat util_pairwise_dist(const arma::mat& X);
RcppExport SEXP _T4transport_util_pairwise_dist(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(util_pairwise_dist(X));
    return rcpp_result_gen;
END_RCPP
}
// util_plan_emd_C
arma::mat util_plan_emd_C(const arma::vec& a, const arma::vec& b, const arma::mat& C);
RcppExport SEXP _T4transport_util_plan_emd_C(SEXP aSEXP, SEXP bSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(util_plan_emd_C(a, b, C));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_T4transport_compute_pdist2", (DL_FUNC) &_T4transport_compute_pdist2, 2},
    {"_T4transport_cpp_mvrnorm", (DL_FUNC) &_T4transport_cpp_mvrnorm, 3},
    {"_T4transport_cpp_ipot20", (DL_FUNC) &_T4transport_cpp_ipot20, 8},
    {"_T4transport_cpp_pwdist", (DL_FUNC) &_T4transport_cpp_pwdist, 6},
    {"_T4transport_cpp_sinkhorn13", (DL_FUNC) &_T4transport_cpp_sinkhorn13, 7},
    {"_T4transport_cpp_barybregman15", (DL_FUNC) &_T4transport_cpp_barybregman15, 9},
    {"_T4transport_cpp_fixed_sinkhorn14", (DL_FUNC) &_T4transport_cpp_fixed_sinkhorn14, 9},
    {"_T4transport_cpp_free_bary_gradient", (DL_FUNC) &_T4transport_cpp_free_bary_gradient, 6},
    {"_T4transport_cpp_single_barycenter", (DL_FUNC) &_T4transport_cpp_single_barycenter, 4},
    {"_T4transport_cpp_free_bary_gradient_init", (DL_FUNC) &_T4transport_cpp_free_bary_gradient_init, 6},
    {"_T4transport_cpp_free_median_PF", (DL_FUNC) &_T4transport_cpp_free_median_PF, 6},
    {"_T4transport_gauss_weiszfeld", (DL_FUNC) &_T4transport_gauss_weiszfeld, 4},
    {"_T4transport_gauss_spdbary16A", (DL_FUNC) &_T4transport_gauss_spdbary16A, 4},
    {"_T4transport_gauss_median_general", (DL_FUNC) &_T4transport_gauss_median_general, 5},
    {"_T4transport_gauss_median_centered", (DL_FUNC) &_T4transport_gauss_median_centered, 4},
    {"_T4transport_routine_bary14C", (DL_FUNC) &_T4transport_routine_bary14C, 10},
    {"_T4transport_routine_bary15B", (DL_FUNC) &_T4transport_routine_bary15B, 10},
    {"_T4transport_util_mvrnorm", (DL_FUNC) &_T4transport_util_mvrnorm, 3},
    {"_T4transport_util_pairwise_sqdist", (DL_FUNC) &_T4transport_util_pairwise_sqdist, 2},
    {"_T4transport_util_pairwise_dist", (DL_FUNC) &_T4transport_util_pairwise_dist, 1},
    {"_T4transport_util_plan_emd_C", (DL_FUNC) &_T4transport_util_plan_emd_C, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_T4transport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
